language: java
sudo: false

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

jdk:
  - oraclejdk8
jobs:
  include:
  - stage: Build and Test on CouchDB 2.3.x
    install:
      - docker pull couchdb:2.3.1
      - docker run -d -p 127.0.0.1:5984:5984 couchdb:2.3.1
      - sleep 15
    script:
      - ./gradlew check integrationTest
  - stage: Build and Test on CouchDB 2.1.x
    install:
      - docker pull couchdb:2.1.2
      - docker run -d -p 127.0.0.1:5984:5984 couchdb:2.1.2
      - sleep 15
    script:
      - ./gradlew check integrationTest
  - stage: Build and Test on CouchDB 1.7.x
    install:
      - docker pull couchdb:1.7.2
      - docker run -d -p 127.0.0.1:5984:5984 couchdb:1.7.2
      - sleep 15
    script:
      - ./gradlew check integrationTest
      
before_install:
  - export TERM=dumb

cache:
  directories:
  - $HOME/.m2
